version: '3'

networks:
  local_network:
    external: true

services:
  app:
    image: nextix_dc:latest
    container_name: nextix_dc_app
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nextix
    ports:
      - 3000:3000
    networks:
      - local_network
volumes:
  data:
